
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label label1;

	private global::Gtk.Alignment alignment4;

	private global::Gtk.Button buttonLimpiar;

	private global::Gtk.HButtonBox hbuttonbox5;

	private global::Gtk.Button button_7;

	private global::Gtk.Button button_8;

	private global::Gtk.Button button_9;

	private global::Gtk.Button buttonSuma;

	private global::Gtk.HButtonBox hbuttonbox4;

	private global::Gtk.Button button_4;

	private global::Gtk.Button button_5;

	private global::Gtk.Button button_6;

	private global::Gtk.Button button_menos;

	private global::Gtk.HButtonBox hbuttonbox3;

	private global::Gtk.Button button_1;

	private global::Gtk.Button button_2;

	private global::Gtk.Button button_3;

	private global::Gtk.Button button_Mult;

	private global::Gtk.HButtonBox hbuttonbox2;

	private global::Gtk.Button button_Cero;

	private global::Gtk.Button button_punto;

	private global::Gtk.Button button_Igual;

	private global::Gtk.Button button_div;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView treeview1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.CanDefault = true;
		this.CanFocus = true;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Calculadora");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(10));
		this.AllowShrink = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		// Container child hbox3.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.Xpad = 5;
		this.label1.Xalign = 0F;
		this.hbox3.Add(this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label1]));
		w1.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.alignment4 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment4.Name = "alignment4";
		this.hbox3.Add(this.alignment4);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.alignment4]));
		w2.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.buttonLimpiar = new global::Gtk.Button();
		this.buttonLimpiar.CanFocus = true;
		this.buttonLimpiar.Name = "buttonLimpiar";
		this.buttonLimpiar.UseUnderline = true;
		this.buttonLimpiar.Label = global::Mono.Unix.Catalog.GetString("C");
		this.hbox3.Add(this.buttonLimpiar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.buttonLimpiar]));
		w3.PackType = ((global::Gtk.PackType)(1));
		w3.Position = 2;
		w3.Expand = false;
		w3.Padding = ((uint)(4));
		this.vbox3.Add(this.hbox3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbuttonbox5 = new global::Gtk.HButtonBox();
		this.hbuttonbox5.Name = "hbuttonbox5";
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this.button_7 = new global::Gtk.Button();
		this.button_7.CanFocus = true;
		this.button_7.Name = "button_7";
		this.button_7.UseUnderline = true;
		this.button_7.Label = global::Mono.Unix.Catalog.GetString("7");
		this.hbuttonbox5.Add(this.button_7);
		global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5[this.button_7]));
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this.button_8 = new global::Gtk.Button();
		this.button_8.CanFocus = true;
		this.button_8.Name = "button_8";
		this.button_8.UseUnderline = true;
		this.button_8.Label = global::Mono.Unix.Catalog.GetString("8");
		this.hbuttonbox5.Add(this.button_8);
		global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5[this.button_8]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this.button_9 = new global::Gtk.Button();
		this.button_9.CanFocus = true;
		this.button_9.Name = "button_9";
		this.button_9.UseUnderline = true;
		this.button_9.Label = global::Mono.Unix.Catalog.GetString("9");
		this.hbuttonbox5.Add(this.button_9);
		global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5[this.button_9]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this.buttonSuma = new global::Gtk.Button();
		this.buttonSuma.CanFocus = true;
		this.buttonSuma.Name = "buttonSuma";
		this.buttonSuma.UseUnderline = true;
		this.buttonSuma.Label = global::Mono.Unix.Catalog.GetString("+");
		this.hbuttonbox5.Add(this.buttonSuma);
		global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5[this.buttonSuma]));
		w8.Position = 3;
		w8.Expand = false;
		w8.Fill = false;
		this.vbox3.Add(this.hbuttonbox5);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbuttonbox5]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbuttonbox4 = new global::Gtk.HButtonBox();
		this.hbuttonbox4.Name = "hbuttonbox4";
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.button_4 = new global::Gtk.Button();
		this.button_4.CanFocus = true;
		this.button_4.Name = "button_4";
		this.button_4.UseUnderline = true;
		this.button_4.Label = global::Mono.Unix.Catalog.GetString("4");
		this.hbuttonbox4.Add(this.button_4);
		global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4[this.button_4]));
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.button_5 = new global::Gtk.Button();
		this.button_5.CanFocus = true;
		this.button_5.Name = "button_5";
		this.button_5.UseUnderline = true;
		this.button_5.Label = global::Mono.Unix.Catalog.GetString("5");
		this.hbuttonbox4.Add(this.button_5);
		global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4[this.button_5]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.button_6 = new global::Gtk.Button();
		this.button_6.CanFocus = true;
		this.button_6.Name = "button_6";
		this.button_6.UseUnderline = true;
		this.button_6.Label = global::Mono.Unix.Catalog.GetString("6");
		this.hbuttonbox4.Add(this.button_6);
		global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4[this.button_6]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.button_menos = new global::Gtk.Button();
		this.button_menos.CanFocus = true;
		this.button_menos.Name = "button_menos";
		this.button_menos.UseUnderline = true;
		this.button_menos.Label = global::Mono.Unix.Catalog.GetString("-");
		this.hbuttonbox4.Add(this.button_menos);
		global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4[this.button_menos]));
		w13.Position = 3;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox3.Add(this.hbuttonbox4);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbuttonbox4]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbuttonbox3 = new global::Gtk.HButtonBox();
		this.hbuttonbox3.Name = "hbuttonbox3";
		// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this.button_1 = new global::Gtk.Button();
		this.button_1.CanFocus = true;
		this.button_1.Name = "button_1";
		this.button_1.UseUnderline = true;
		this.button_1.Label = global::Mono.Unix.Catalog.GetString("1");
		this.hbuttonbox3.Add(this.button_1);
		global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.button_1]));
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this.button_2 = new global::Gtk.Button();
		this.button_2.CanFocus = true;
		this.button_2.Name = "button_2";
		this.button_2.UseUnderline = true;
		this.button_2.Label = global::Mono.Unix.Catalog.GetString("2");
		this.hbuttonbox3.Add(this.button_2);
		global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.button_2]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this.button_3 = new global::Gtk.Button();
		this.button_3.CanFocus = true;
		this.button_3.Name = "button_3";
		this.button_3.UseUnderline = true;
		this.button_3.Label = global::Mono.Unix.Catalog.GetString("3");
		this.hbuttonbox3.Add(this.button_3);
		global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.button_3]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this.button_Mult = new global::Gtk.Button();
		this.button_Mult.CanFocus = true;
		this.button_Mult.Name = "button_Mult";
		this.button_Mult.UseUnderline = true;
		this.button_Mult.Label = global::Mono.Unix.Catalog.GetString("*");
		this.hbuttonbox3.Add(this.button_Mult);
		global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.button_Mult]));
		w18.Position = 3;
		w18.Expand = false;
		w18.Fill = false;
		this.vbox3.Add(this.hbuttonbox3);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbuttonbox3]));
		w19.Position = 3;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbuttonbox2 = new global::Gtk.HButtonBox();
		this.hbuttonbox2.Name = "hbuttonbox2";
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.button_Cero = new global::Gtk.Button();
		this.button_Cero.CanFocus = true;
		this.button_Cero.Name = "button_Cero";
		this.button_Cero.UseUnderline = true;
		this.button_Cero.Label = global::Mono.Unix.Catalog.GetString("0");
		this.hbuttonbox2.Add(this.button_Cero);
		global::Gtk.ButtonBox.ButtonBoxChild w20 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.button_Cero]));
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.button_punto = new global::Gtk.Button();
		this.button_punto.CanFocus = true;
		this.button_punto.Name = "button_punto";
		this.button_punto.UseUnderline = true;
		this.button_punto.Label = global::Mono.Unix.Catalog.GetString(".");
		this.hbuttonbox2.Add(this.button_punto);
		global::Gtk.ButtonBox.ButtonBoxChild w21 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.button_punto]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.button_Igual = new global::Gtk.Button();
		this.button_Igual.CanDefault = true;
		this.button_Igual.CanFocus = true;
		this.button_Igual.Name = "button_Igual";
		this.button_Igual.UseUnderline = true;
		this.button_Igual.Label = global::Mono.Unix.Catalog.GetString("=");
		this.hbuttonbox2.Add(this.button_Igual);
		global::Gtk.ButtonBox.ButtonBoxChild w22 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.button_Igual]));
		w22.Position = 2;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.button_div = new global::Gtk.Button();
		this.button_div.CanFocus = true;
		this.button_div.Name = "button_div";
		this.button_div.UseUnderline = true;
		this.button_div.Label = global::Mono.Unix.Catalog.GetString("/");
		this.hbuttonbox2.Add(this.button_div);
		global::Gtk.ButtonBox.ButtonBoxChild w23 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.button_div]));
		w23.Position = 3;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox3.Add(this.hbuttonbox2);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbuttonbox2]));
		w24.Position = 4;
		w24.Expand = false;
		w24.Fill = false;
		this.hbox1.Add(this.vbox3);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
		w25.Position = 0;
		w25.Expand = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeview1 = new global::Gtk.TreeView();
		this.treeview1.CanFocus = true;
		this.treeview1.Name = "treeview1";
		this.GtkScrolledWindow.Add(this.treeview1);
		this.hbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
		w27.Position = 1;
		this.Add(this.hbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 627;
		this.DefaultHeight = 209;
		this.button_Igual.HasDefault = true;
		this.HasDefault = true;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.OnKeyPressEvent);
		this.buttonLimpiar.Clicked += new global::System.EventHandler(this.OnButtonLimpiarClicked);
		this.button_7.Clicked += new global::System.EventHandler(this.OnButton7Clicked);
		this.button_8.Clicked += new global::System.EventHandler(this.OnButton8Clicked);
		this.button_9.Clicked += new global::System.EventHandler(this.OnButton9Clicked);
		this.buttonSuma.Clicked += new global::System.EventHandler(this.OnButtonSumaClicked);
		this.button_4.Clicked += new global::System.EventHandler(this.OnButton4Clicked);
		this.button_5.Clicked += new global::System.EventHandler(this.OnButton5Clicked);
		this.button_6.Clicked += new global::System.EventHandler(this.OnButton6Clicked);
		this.button_menos.Clicked += new global::System.EventHandler(this.OnButtonMenosClicked);
		this.button_1.Clicked += new global::System.EventHandler(this.OnButton1Clicked);
		this.button_2.Clicked += new global::System.EventHandler(this.OnButton2Clicked);
		this.button_3.Clicked += new global::System.EventHandler(this.OnButton3Clicked);
		this.button_Mult.Clicked += new global::System.EventHandler(this.OnButtonMultClicked);
		this.button_Cero.Clicked += new global::System.EventHandler(this.OnButtonCeroClicked);
		this.button_punto.Clicked += new global::System.EventHandler(this.OnButtonPuntoClicked);
		this.button_Igual.Clicked += new global::System.EventHandler(this.OnButtonIgualClicked);
		this.button_div.Clicked += new global::System.EventHandler(this.OnButtonDivClicked);
		this.treeview1.RowActivated += new global::Gtk.RowActivatedHandler(this.OnTreeview1RowActivated);
	}
}
